---
name: Staging
on:
  workflow_dispatch:
    inputs:
      baseSha:
        description: "Use base SHA commit to deploy from (empty string defaults to last commit before HEAD)"
        type: string
        required: false
        default: ""
      deployAll:
        description: "Force deploy all files"
        type: boolean
        default: false
jobs:
  deployment:
    name: Deployment
    uses: AdobeDocs/adp-devsite-workflow/.github/workflows/deploy.yml@main
    with:
      env: stage
      baseSha: ${{ inputs.baseSha }}
      deployAll: ${{ inputs.deployAll }}
