---
name: Test
on:
  pull_request:
    paths:
      - 'src/pages/**'
      - 'tests/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: npm run test
